apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-reportes
  namespace: muni-valle-sol
  labels:
    app: ms-reportes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-reportes
  template:
    metadata:
      labels:
        app: ms-reportes
    spec:
      containers:
        - name: ms-reportes
          image: lsn33/muni-valle-sol-ms-reportes:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: muni-secrets
                  key: reportes-db-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: muni-secrets
                  key: reportes-db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: muni-secrets
                  key: reportes-db-password
            - name: SERVER_PORT
              value: "8082"
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 45
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
